package com.example.OrdersApi.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

@Component
public class DatabaseInitializer {

    private static final Logger logger =
            LoggerFactory.getLogger(DatabaseInitializer.class);

    public boolean initialize() {

        String jdbcUrl = System.getenv("POSTGRES_JDBC_URL");
        String username = System.getenv("POSTGRES_USER");
        String password = System.getenv("POSTGRES_PASSWORD");

        if (jdbcUrl == null || jdbcUrl.isBlank()
                || username == null || username.isBlank()
                || password == null || password.isBlank()) {

            logger.warn("Variables de PostgreSQL no configuradas.");
            return false;
        }

        try {
            String databaseName = extractDatabaseName(jdbcUrl);
            String adminUrl = buildAdminUrl(jdbcUrl);

            createDatabaseIfNotExists(
                    adminUrl,
                    username,
                    password,
                    databaseName
            );

            createOrdersTable(
                    jdbcUrl,
                    username,
                    password
            );

            logger.info(
                    "PostgreSQL inicializado correctamente. Base de datos: {}",
                    databaseName
            );

            return true;

        } catch (Exception ex) {

            logger.error(
                    "No fue posible inicializar PostgreSQL.",
                    ex
            );

            return false;
        }
    }

    private void createDatabaseIfNotExists(
            String adminUrl,
            String username,
            String password,
            String databaseName) throws SQLException {

        try (Connection connection =
                     DriverManager.getConnection(
                             adminUrl,
                             username,
                             password)) {

            String sql =
                    "SELECT 1 FROM pg_database WHERE datname = ?";

            try (PreparedStatement statement =
                         connection.prepareStatement(sql)) {

                statement.setString(1, databaseName);

                try (ResultSet resultSet =
                             statement.executeQuery()) {

                    if (resultSet.next()) {
                        logger.info(
                                "La base de datos {} ya existe.",
                                databaseName
                        );
                        return;
                    }
                }
            }

            String createDatabaseSql =
                    "CREATE DATABASE " + quoteIdentifier(databaseName);

            try (Statement statement =
                         connection.createStatement()) {

                statement.executeUpdate(createDatabaseSql);

                logger.info(
                        "Base de datos {} creada correctamente.",
                        databaseName
                );
            }
        }
    }

    private void createOrdersTable(
            String jdbcUrl,
            String username,
            String password) throws SQLException {

        String sql = """
                CREATE TABLE IF NOT EXISTS orders (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    titulo_libro VARCHAR(255) NOT NULL,
                    nombre_usuario VARCHAR(255) NOT NULL,
                    precio NUMERIC(10, 2) NOT NULL,
                    fecha_hora_compra TIMESTAMP NOT NULL
                )
                """;

        try (Connection connection =
                     DriverManager.getConnection(
                             jdbcUrl,
                             username,
                             password);
             Statement statement =
                     connection.createStatement()) {

            statement.executeUpdate(sql);

            logger.info(
                    "Tabla orders verificada correctamente."
            );
        }
    }

    private String extractDatabaseName(String jdbcUrl) {

        String url = jdbcUrl;

        int queryIndex = url.indexOf('?');

        if (queryIndex >= 0) {
            url = url.substring(0, queryIndex);
        }

        int lastSlash = url.lastIndexOf('/');

        if (lastSlash < 0 || lastSlash == url.length() - 1) {
            throw new IllegalArgumentException(
                    "POSTGRES_JDBC_URL no contiene una base de datos."
            );
        }

        return url.substring(lastSlash + 1);
    }

    private String buildAdminUrl(String jdbcUrl) {

        int queryIndex = jdbcUrl.indexOf('?');

        String baseUrl =
                queryIndex >= 0
                        ? jdbcUrl.substring(0, queryIndex)
                        : jdbcUrl;

        String query =
                queryIndex >= 0
                        ? jdbcUrl.substring(queryIndex)
                        : "";

        int lastSlash = baseUrl.lastIndexOf('/');

        if (lastSlash < 0) {
            throw new IllegalArgumentException(
                    "POSTGRES_JDBC_URL no es válido."
            );
        }

        return baseUrl.substring(0, lastSlash)
                + "/postgres"
                + query;
    }

    private String quoteIdentifier(String identifier) {

        return "\""
                + identifier.replace("\"", "\"\"")
                + "\"";
    }
}